pipeline {
         agent any
          tools { 
        maven 'maven-3.6.0' 
       
    }
         environment {
    PATH = "C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\bin;${env.PATH}"; 
         }
         stages {
                  withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/sunnybg111/lalu.git',  branch: 'master'
        }
                  
                  
                 stage('One') {
                         
                          
                          
                 steps {
                          dir('demo'){
                                          bat 'mvn clean install'
                          }
                          
                     }
                 }
         }
} 
