pipeline {
         agent any
          tools { 
        maven 'maven-3.6.0' 
       
    }
         environment {
    PATH = "C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\bin;${env.PATH}"; 
         }
         stages {
                  

        
                  
                 
                          
                          
                 steps {
                          dir('demo'){
                                   
                                   git url: 'https://github.com/piomin/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
                                          bat 'mvn clean install'
                          }
                          
                     }
                 }
         }

}
