pipeline {
         agent any
          tools { 
        maven 'maven-3.6.0' 
       
    }
         environment {
    PATH = "C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\bin;${env.PATH}"; 
         }
         stages {
                  stage('one'){
                  
                           steps{
                           
                           git url:'https://github.com/sunnybg111/lalu.git', branch: 'master'
                           }
                  }
                  
                 stage('two') {
                 steps { 
                                          bat 'mvn clean install'
                     }
                 }
                  
                  
                  
                  
         }
} 
